---
development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292

production:
  API_URL: https://wefix-api.herokuapp.com/api/v1
  APP_URL: https://wefix-app.herokuapp.com